In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame

In [3]:
# Carichiamo i dati relativi al campionato di serie A 2015-16 memorizzati in un file csv (comma separated values)
# utilizzando il prefisso 'r' (raw) nel path del file per non dover raddoppiare manualmente gli slash (\\)

In [4]:
pd.read_csv(r'campionato.csv')

,Squadra,Pt,G,V,N,P,Rf,Rs,V.1,N.1,P.1,Rf.1,Rs.1,V.2,N.2,P.2,Rf.2,Rs.2
0,Juventus,91,38,29,4,5,75,20,16,2,1,37,6,13,2,4,38,14
1,Napoli,82,38,25,7,6,80,32,16,3,0,49,12,9,4,6,31,20
2,Roma,80,38,23,11,4,83,41,13,5,1,44,17,10,6,3,39,24
3,Inter,67,38,20,7,11,50,38,13,2,4,29,15,7,5,7,21,23
4,Fiorentina,64,38,18,10,10,60,42,11,5,3,34,16,7,5,7,26,26
5,Sassuolo,61,38,16,13,9,49,40,8,8,3,25,20,8,5,6,24,20
6,Milan,57,38,15,12,11,49,43,9,6,4,28,22,6,6,7,21,21
7,Lazio,54,38,15,9,14,52,52,10,3,6,32,23,5,6,8,20,29
8,Chievo,50,38,13,11,14,43,45,7,8,4,25,18,6,3,10,18,27
9,Genoa,46,38,13,7,18,45,48,10,3,6,29,19,3,4,12,16,29
10,Empoli,46,38,12,10,16,40,49,7,6,6,22,20,5,4,10,18,29
11,Torino,45,38,12,9,17,52,55,6,6,7,25,25,6,3,10,27,30
12,Atalanta,45,38,11,12,15,41,47,8,6,5,27,21,3,6,10,14,26
13,Bologna,42,38,11,9,18,33,45,5,5,9,20,21,6,4,9,13,24
14,Sampdoria,40,38,10,10,18,48,61,8,4,7,29,25,2,6,11,19,36
15,Palermo,39,38,10,9,19,38,65,6,4,9,24,30,4,5,10,14,35
16,Udinese,39,38,10,9,19,35,60,6,4,9,18,28,4,5,10,17,32
17,Carpi,38,38,9,11,18,37,57,6,5,8,23,26,3,6,10,14,31
18,Frosinone,31,38,8,7,23,35,76,6,4,9,18,26,2,3,14,17,50
19,Verona,28,38,5,13,20,34,63,4,6,9,21,30,1,7,11,13,33

In [ ]:
# Ora memorizziamo il tutto in un DataFrame per una migliore gestione

In [5]:
df_campionato = pd.read_csv(r'campionato.csv')

In [6]:
# Per prima cosa elenchiamo tutte le colonne

In [7]:
df_campionato.columns

Index(['Squadra', 'Pt', 'G', 'V', 'N', 'P', 'Rf', 'Rs', 'V.1', 'N.1', 'P.1',
       'Rf.1', 'Rs.1', 'V.2', 'N.2', 'P.2', 'Rf.2', 'Rs.2'],
      dtype='object')

In [8]:
# Volendo visualizzare una specifica colonna basta indicarne il nome

In [9]:
df_campionato.Squadra

0       Juventus
1         Napoli
2           Roma
3          Inter
4     Fiorentina
5       Sassuolo
6          Milan
7          Lazio
8         Chievo
9          Genoa
10        Empoli
11        Torino
12      Atalanta
13       Bologna
14     Sampdoria
15       Palermo
16       Udinese
17         Carpi
18     Frosinone
19        Verona
Name: Squadra, dtype: object

In [10]:
df_campionato.Pt

0     91
1     82
2     80
3     67
4     64
5     61
6     57
7     54
8     50
9     46
10    46
11    45
12    45
13    42
14    40
15    39
16    39
17    38
18    31
19    28
Name: Pt, dtype: int64

In [11]:
# La visualizzazione dei record si ottiene con head(N) dove N è il numero di righe da includere. Se non specificato 
# si considerano le prime 5 (indici da 0 a 4)

In [12]:
df_campionato.head()

,Squadra,Pt,G,V,N,P,Rf,Rs,V.1,N.1,P.1,Rf.1,Rs.1,V.2,N.2,P.2,Rf.2,Rs.2
0,Juventus,91,38,29,4,5,75,20,16,2,1,37,6,13,2,4,38,14
1,Napoli,82,38,25,7,6,80,32,16,3,0,49,12,9,4,6,31,20
2,Roma,80,38,23,11,4,83,41,13,5,1,44,17,10,6,3,39,24
3,Inter,67,38,20,7,11,50,38,13,2,4,29,15,7,5,7,21,23
4,Fiorentina,64,38,18,10,10,60,42,11,5,3,34,16,7,5,7,26,26

In [13]:
df_campionato.head(10)

,Squadra,Pt,G,V,N,P,Rf,Rs,V.1,N.1,P.1,Rf.1,Rs.1,V.2,N.2,P.2,Rf.2,Rs.2
0,Juventus,91,38,29,4,5,75,20,16,2,1,37,6,13,2,4,38,14
1,Napoli,82,38,25,7,6,80,32,16,3,0,49,12,9,4,6,31,20
2,Roma,80,38,23,11,4,83,41,13,5,1,44,17,10,6,3,39,24
3,Inter,67,38,20,7,11,50,38,13,2,4,29,15,7,5,7,21,23
4,Fiorentina,64,38,18,10,10,60,42,11,5,3,34,16,7,5,7,26,26
5,Sassuolo,61,38,16,13,9,49,40,8,8,3,25,20,8,5,6,24,20
6,Milan,57,38,15,12,11,49,43,9,6,4,28,22,6,6,7,21,21
7,Lazio,54,38,15,9,14,52,52,10,3,6,32,23,5,6,8,20,29
8,Chievo,50,38,13,11,14,43,45,7,8,4,25,18,6,3,10,18,27
9,Genoa,46,38,13,7,18,45,48,10,3,6,29,19,3,4,12,16,29

In [14]:
# Per accedere alle ultime righe si può ricorrere a tail(N)

In [15]:
df_campionato.tail()

,Squadra,Pt,G,V,N,P,Rf,Rs,V.1,N.1,P.1,Rf.1,Rs.1,V.2,N.2,P.2,Rf.2,Rs.2
15,Palermo,39,38,10,9,19,38,65,6,4,9,24,30,4,5,10,14,35
16,Udinese,39,38,10,9,19,35,60,6,4,9,18,28,4,5,10,17,32
17,Carpi,38,38,9,11,18,37,57,6,5,8,23,26,3,6,10,14,31
18,Frosinone,31,38,8,7,23,35,76,6,4,9,18,26,2,3,14,17,50
19,Verona,28,38,5,13,20,34,63,4,6,9,21,30,1,7,11,13,33

In [16]:
df_campionato.tail(10)

,Squadra,Pt,G,V,N,P,Rf,Rs,V.1,N.1,P.1,Rf.1,Rs.1,V.2,N.2,P.2,Rf.2,Rs.2
10,Empoli,46,38,12,10,16,40,49,7,6,6,22,20,5,4,10,18,29
11,Torino,45,38,12,9,17,52,55,6,6,7,25,25,6,3,10,27,30
12,Atalanta,45,38,11,12,15,41,47,8,6,5,27,21,3,6,10,14,26
13,Bologna,42,38,11,9,18,33,45,5,5,9,20,21,6,4,9,13,24
14,Sampdoria,40,38,10,10,18,48,61,8,4,7,29,25,2,6,11,19,36
15,Palermo,39,38,10,9,19,38,65,6,4,9,24,30,4,5,10,14,35
16,Udinese,39,38,10,9,19,35,60,6,4,9,18,28,4,5,10,17,32
17,Carpi,38,38,9,11,18,37,57,6,5,8,23,26,3,6,10,14,31
18,Frosinone,31,38,8,7,23,35,76,6,4,9,18,26,2,3,14,17,50
19,Verona,28,38,5,13,20,34,63,4,6,9,21,30,1,7,11,13,33

In [17]:
# Mentre volendo accedere ad una specifica riga basta specificarne il relativo indice

In [18]:
df_campionato.ix[3]

Squadra    Inter
Pt            67
G             38
V             20
N              7
P             11
Rf            50
Rs            38
V.1           13
N.1            2
P.1            4
Rf.1          29
Rs.1          15
V.2            7
N.2            5
P.2            7
Rf.2          21
Rs.2          23
Name: 3, dtype: object

In [19]:
# Possiamo anche creare un nuovo DataFrame includendo solo alcune colonne

In [20]:
df_campionato2 = DataFrame(df_campionato, columns=['Squadra','Pt','G','V','N','P'])

In [21]:
df_campionato2

       Squadra  Pt   G   V   N   P
0     Juventus  91  38  29   4   5
1       Napoli  82  38  25   7   6
2         Roma  80  38  23  11   4
3        Inter  67  38  20   7  11
4   Fiorentina  64  38  18  10  10
5     Sassuolo  61  38  16  13   9
6        Milan  57  38  15  12  11
7        Lazio  54  38  15   9  14
8       Chievo  50  38  13  11  14
9        Genoa  46  38  13   7  18
10      Empoli  46  38  12  10  16
11      Torino  45  38  12   9  17
12    Atalanta  45  38  11  12  15
13     Bologna  42  38  11   9  18
14   Sampdoria  40  38  10  10  18
15     Palermo  39  38  10   9  19
16     Udinese  39  38  10   9  19
17       Carpi  38  38   9  11  18
18   Frosinone  31  38   8   7  23
19      Verona  28  38   5  13  20

In [22]:
# Il dataframe può essere modificato ad esempio aggiungendo la colonna relativa allo stadio in cui ciascuna 
# squadra ha disputato le proprie gare interne

In [23]:
df_campionato2['Stadio'] = "S. Siro"

In [24]:
df_campionato2

       Squadra  Pt   G   V   N   P   Stadio
0     Juventus  91  38  29   4   5  S. Siro
1       Napoli  82  38  25   7   6  S. Siro
2         Roma  80  38  23  11   4  S. Siro
3        Inter  67  38  20   7  11  S. Siro
4   Fiorentina  64  38  18  10  10  S. Siro
5     Sassuolo  61  38  16  13   9  S. Siro
6        Milan  57  38  15  12  11  S. Siro
7        Lazio  54  38  15   9  14  S. Siro
8       Chievo  50  38  13  11  14  S. Siro
9        Genoa  46  38  13   7  18  S. Siro
10      Empoli  46  38  12  10  16  S. Siro
11      Torino  45  38  12   9  17  S. Siro
12    Atalanta  45  38  11  12  15  S. Siro
13     Bologna  42  38  11   9  18  S. Siro
14   Sampdoria  40  38  10  10  18  S. Siro
15     Palermo  39  38  10   9  19  S. Siro
16     Udinese  39  38  10   9  19  S. Siro
17       Carpi  38  38   9  11  18  S. Siro
18   Frosinone  31  38   8   7  23  S. Siro
19      Verona  28  38   5  13  20  S. Siro

In [25]:
# Si può osservare come venga associato lo stesso valore a tutte le righe

In [26]:
# Per rimuovere la colonna 'Stadio'

In [27]:
del df_campionato2['Stadio']

In [28]:
df_campionato2

       Squadra  Pt   G   V   N   P
0     Juventus  91  38  29   4   5
1       Napoli  82  38  25   7   6
2         Roma  80  38  23  11   4
3        Inter  67  38  20   7  11
4   Fiorentina  64  38  18  10  10
5     Sassuolo  61  38  16  13   9
6        Milan  57  38  15  12  11
7        Lazio  54  38  15   9  14
8       Chievo  50  38  13  11  14
9        Genoa  46  38  13   7  18
10      Empoli  46  38  12  10  16
11      Torino  45  38  12   9  17
12    Atalanta  45  38  11  12  15
13     Bologna  42  38  11   9  18
14   Sampdoria  40  38  10  10  18
15     Palermo  39  38  10   9  19
16     Udinese  39  38  10   9  19
17       Carpi  38  38   9  11  18
18   Frosinone  31  38   8   7  23
19      Verona  28  38   5  13  20